version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    networks:
      local-dep:
        ipv4_address: 172.19.0.5
    ports:
      - "27017:27017"
    restart: always

  backend:
    container_name: book-store-be
    image: emagmir/docker-bs-be
    networks:
      local-dep:
        ipv4_address: 172.19.0.6
    ports:
      - "8000:8000"
    restart: always

  frontend:
    container_name: book-store-fe
    image: emagmir/docker-bs-fe
    networks:
      local-dep:
        ipv4_address: 172.19.0.7
    ports:
      - "3000:3000"
    restart: always

networks:
  local-dep:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1