#Base image
FROM python:3-slim

# Set the working directory inside the container
WORKDIR /app

COPY . .

#install libraries
RUN pip install -r requirements.txt

RUN pip install uvicorn

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]