apiVersion: v1
kind: Service
metadata:
  name: bs-be-dep
spec:
  selector:
    app: bs-be-dep
  ports:
  - port: 8000
    targetPort: bs-be-port
    name: bs-be-svc
    protocol: TCP
  type: ClusterIP