apiVersion: v1
kind: Service
metadata:
  name: bookstore-be-dep
spec:
  selector:
    app: bookstore-be-dep
  ports:
  - port: 8000
    targetPort: book-store-be-port
    name: bookstore-be-svc
    protocol: TCP
  type: ClusterIP