apiVersion: apps/v1
kind: Deployment
metadata:
  name: bs-fe-dep
  labels:
    app: bs-fe-dep
    environment: production
spec:
  selector:
    matchLabels:
      app: bs-fe-dep
  template:
    metadata:
      labels:
        app: bs-fe-dep
    spec:
      containers:
      - name: bs-fe
        image: emagmir/book-store-fe
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: bs-fe-port
          containerPort: 3000
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        effect: "NoSchedule"