apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-fe-dep
  labels:
    app: bookstore-fe-dep
    environment: production
spec:
  selector:
    matchLabels:
      app: bookstore-fe-dep
  template:
    metadata:
      labels:
        app: bookstore-fe-dep
    spec:
      containers:
      - name: bookstore-fe
        image: emagmir/book-store-fe
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: bookstore-fe-port
          containerPort: 3000