apiVersion: apps/v1
kind: Deployment
metadata:
  name: bs-be-dep
  labels:
    app: bs-be-dep
    environment: production
spec:
  selector:
    matchLabels:
      app: bs-be-dep
  template:
    metadata:
      labels:
        app: bs-be-dep
    spec:
      serviceAccountName: book-store-sa
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "aws-secrets-class"
      containers:
      - name: bs-be
        image: emagmir/bs-be-eks
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: bs-be-port
          containerPort: 8000
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        effect: "NoSchedule"