apiVersion: v1
kind: Service
metadata:
  name: bs-fe-dep
spec:
  selector:
    app: bs-fe-dep
  ports:
  - port: 3000
    nodePort: 30008
    targetPort: bs-fe-port
    name: bs-fe-port-svc
    protocol: TCP
  type: NodePort