apiVersion: v1
kind: Service
metadata:
  name: mdb-service
spec:
  selector:
    app: bookstore # Corrected to match StatefulSet labels
  ports:
  - port: 27017
    name: mdb-port-svc
    targetPort: mongoport
  type: ClusterIP
