apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: bookstore # has to match .spec.template.metadata.labels
  serviceName: "mongo"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: bookstore # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:4.4.6
        ports:
        - containerPort: 27017
          name: mongoport
        volumeMounts:
        - name: mongovolume
          mountPath: /persistent_data
  volumeClaimTemplates:
  - metadata:
      name: monovolume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 1Gi