apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvolume01
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  hostPath: #this mount will be available only on this node
    path: /persistent_data